### ISSUE TITLE
Is this script works on debian-like OS only?

### ISSUE THREAD

**Issue by ice1x** [Ethical-H4CK3R/YouTubeViews#11]
Hi.

I got on OSX error:
$ python ../youtube.py 300 ../youtubeLinks.txt 7 10000
Installing Tor ...
Please Install Tor

And found that it related to the function:
 def installTor(self):
  self.connection()
  if not self.alive:return
  print 'Installing Tor ...'
  shell('echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list \
         && apt-get update && apt-get install tor -y && apt autoremove -y')

So why don't you mention that this script is for debian-like Linux only?
Have you OSX version?

**Comment by Ethical-H4CK3R** [comment]
Did you tried the YouTubeCP folder, that might work?

**Comment by ice1x** [comment]
Unfortunately for me - the same behaviour:
YouTubeCP user$ python ../youtube.py 300 ../youtubeLinks.txt 7 10000
Installing Tor ...
Please Install Tor

**Comment by ice1x** [comment]
Oops - i had use incorrect path to the script with double-dots
This works fine:
YouTubeCP user$ python ./youtube.py 300 ../youtubeLinks.txt 7 10000
